### ISSUE TITLE
Trained model and scripts to run the tool

### ISSUE THREAD

**Issue by arefeen** [likesum/deepPolyA#1]
Hi,

I like to use DeeReCT-PolyA tool to predict PASes. Therefore, do you have a trained model that I can use directly? Moreover, what kind of input data the tool expects? If you don't have the trained model, can you please provide the necessary scripts to train a model? Moreover, what script I can use to use the trained model with an input file?

Thanks in advance for your help.

**Comment by likesum** [comment]
Hi,

Thanks for the interest in our work. We are planning on releasing the pre-trained models and the fine-tuning code soon. Hopefully I will get to it by the end of this week.

**Comment by arefeen** [comment]
Thanks a lot for your reply.

I am eagerly waiting for the updates.

**Comment by likesum** [comment]
@arefeen Please check out the updated repo for pre-trained models and some demo code along with the instructions on how to run them.

Thanks,
Zhihao

**Comment by arefeen** [comment]
Hi,

I have tried to run the trained model using following command:
python test.py data/human/dragon_polyA_data/positive5fold/AAAAAG_fold_1.txt models/dragon_hparam.npz

It gives error:
File "/.conda/envs/tensorflow_p3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 262, in __getitem__
    raise KeyError("%s is not a file in the archive" % key)
KeyError: 'conv_weights is not a file in the archive'

I am using python 3.6, tensorflow 1.13.1 and numpy 1.16.2.
