### ISSUE TITLE
Output softmax score instead of binary

### ISSUE THREAD

**Issue by cheny19** [likesum/deepPolyA#2]
Hi developers,

I would like to use DeeReCT-PolyA to predict some PAS, and I'm wondering if it's possible to get softmax scores as output instead of the current version, binary classes. 

Thanks,
Chen

**Comment by likesum** [comment]
Hi,

Our model is to solve a binary classification problem, i.e. if a PAS is true/false. So do you mean you want to get the softmax score for each of these two classes?

If so, the tf node to compute the softmax score is defined here https://github.com/likesum/DeeReCT-PolyA/blob/master/model.py#L88. For example, in the testing code, we get the scores in this line https://github.com/likesum/DeeReCT-PolyA/blob/master/test.py#L68.

**Comment by cheny19** [comment]
Cool, thanks!
